// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { CandidateAnalyseCandidateCvData, CandidateAnalyseCandidateCvResponse, CandidateGetCandidateAnalysisResultData, CandidateGetCandidateAnalysisResultResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, JobAnalyseJobData, JobAnalyseJobResponse, JobsReadJobsData, JobsReadJobsResponse, JobsCreateJobData, JobsCreateJobResponse, JobsReadJobData, JobsReadJobResponse, JobsUpdateJobData, JobsUpdateJobResponse, JobsDeleteJobData, JobsDeleteJobResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, ScoreAnalyseScoreData, ScoreAnalyseScoreResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, ScoreSaveScoreAnalysisData, ScoreSaveScoreAnalysisResponse, ScoreGetScoreAnalysisByJobData, ScoreGetScoreAnalysisByJobResponse, ScoreGetScoreAnalysisByJobAndCandidateData, ScoreGetScoreAnalysisByJobAndCandidateResponse } from './types.gen';

export class CandidateService {
    /**
     * Analyse Candidate Cv
     * Save a CV file to the candidate upload directory and analyze it.
     * @param data The data for the request.
     * @param data.formData
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static analyseCandidateCv(data: CandidateAnalyseCandidateCvData): CancelablePromise<CandidateAnalyseCandidateCvResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/candidate/analyse_candidate',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Candidate Analysis Result
     * Retrieve analysis result for a specific file from the database.
     * Can search by either timestamped filename or original filename.
     * @param data The data for the request.
     * @param data.fileName
     * @returns CandidateAnalysisPublic Successful Response
     * @throws ApiError
     */
    public static getCandidateAnalysisResult(data: CandidateGetCandidateAnalysisResultData): CancelablePromise<CandidateGetCandidateAnalysisResultResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/candidate/analysis_result/{file_name}',
            path: {
                file_name: data.fileName
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class JobService {
    /**
     * Analyse Job
     * @param data The data for the request.
     * @param data.requestBody
     * @returns JobResponseSchema Successful Response
     * @throws ApiError
     */
    public static analyseJob(data: JobAnalyseJobData): CancelablePromise<JobAnalyseJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/job/analyse_job',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class JobsService {
    /**
     * Read Jobs
     * Retrieve jobs.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.title
     * @param data.description
     * @param data.createdAt
     * @returns JobsPublic Successful Response
     * @throws ApiError
     */
    public static readJobs(data: JobsReadJobsData = {}): CancelablePromise<JobsReadJobsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/jobs/',
            query: {
                skip: data.skip,
                limit: data.limit,
                title: data.title,
                description: data.description,
                created_at: data.createdAt
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Job
     * Create new job.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static createJob(data: JobsCreateJobData): CancelablePromise<JobsCreateJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/jobs/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Job
     * Get job by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static readJob(data: JobsReadJobData): CancelablePromise<JobsReadJobResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/jobs/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Job
     * Update a job.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns JobPublic Successful Response
     * @throws ApiError
     */
    public static updateJob(data: JobsUpdateJobData): CancelablePromise<JobsUpdateJobResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/jobs/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Job
     * Delete a job.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteJob(data: JobsDeleteJobData): CancelablePromise<JobsDeleteJobResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/jobs/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class ScoreService {
    /**
     * Analyse Score
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static analyseScore(data: ScoreAnalyseScoreData): CancelablePromise<ScoreAnalyseScoreResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/score/score_analyse',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Save Score Analysis
     * Save score analysis result to the database.
     * @param data The data for the request.
     * @param data.jobId
     * @param data.candidateFileName
     * @param data.scoreResult
     * @returns ScoreAnalysisPublic Successful Response
     * @throws ApiError
     */
    public static saveScoreAnalysis(data: ScoreSaveScoreAnalysisData): CancelablePromise<ScoreSaveScoreAnalysisResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/score/save_score_analysis',
            query: {
                'job_id': data.jobId,
                'candidate_file_name': data.candidateFileName,
            },
            body: data.scoreResult,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Score Analysis By Job
     * Retrieve all score analysis results for a specific job.
     * @param data The data for the request.
     * @param data.jobId
     * @returns ScoreAnalysisPublic Successful Response
     * @throws ApiError
     */
    public static getScoreAnalysisByJob(data: ScoreGetScoreAnalysisByJobData): CancelablePromise<ScoreGetScoreAnalysisByJobResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/score/score_analysis/{job_id}',
            path: {
                'job_id': data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Score Analysis By Job And Candidate
     * Retrieve score analysis result for a specific job and candidate file.
     * @param data The data for the request.
     * @param data.jobId
     * @param data.candidateFileName
     * @returns ScoreAnalysisPublic Successful Response
     * @throws ApiError
     */
    public static getScoreAnalysisByJobAndCandidate(data: ScoreGetScoreAnalysisByJobAndCandidateData): CancelablePromise<ScoreGetScoreAnalysisByJobAndCandidateResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/score/score_analysis/{job_id}/{candidate_file_name}',
            path: {
                'job_id': data.jobId,
                'candidate_file_name': data.candidateFileName
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
    
}