// This file is auto-generated by @hey-api/openapi-ts

export type Body_candidate_analyse_candidate_cv = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CandidateAnalysisPublic = {
    id: string;
    file_name: string;
    original_file_name: (string | null);
    analysis_result: string;
    created_at: string;
    updated_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobAnalyzeRequest = {
    title: string;
    description?: (string | null);
    id?: (string | null);
    owner_id?: (string | null);
    files?: (string | null);
};

export type JobCreate = {
    title: string;
    description?: (string | null);
    files?: (string | null);
};

export type JobPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    files?: (string | null);
    analysis_result?: (string | null);
    created_at: string;
};

export type JobResponseSchema = {
    degree: Array<unknown>;
    experience: Array<unknown>;
    technical_skill: Array<unknown>;
    responsibility: Array<unknown>;
    certificate: Array<unknown>;
    soft_skill: Array<unknown>;
};

export type JobsPublic = {
    data: Array<JobPublic>;
    count: number;
};

export type JobUpdate = {
    title?: (string | null);
    description?: (string | null);
    files?: (string | null);
    analysis_result?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ScoreSchema = {
    candidate: {
        [key: string]: unknown;
    };
    job: {
        [key: string]: unknown;
    };
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CandidateAnalyseCandidateCvData = {
    formData: Body_candidate_analyse_candidate_cv;
};

export type CandidateAnalyseCandidateCvResponse = (unknown);

export type CandidateGetCandidateAnalysisResultData = {
    fileName: string;
};

export type CandidateGetCandidateAnalysisResultResponse = (CandidateAnalysisPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobAnalyseJobData = {
    requestBody: JobAnalyzeRequest;
};

export type JobAnalyseJobResponse = (JobResponseSchema);

export type JobsReadJobsData = {
    createdAt?: (string | null);
    description?: (string | null);
    limit?: number;
    skip?: number;
    title?: (string | null);
};

export type JobsReadJobsResponse = (JobsPublic);

export type JobsCreateJobData = {
    requestBody: JobCreate;
};

export type JobsCreateJobResponse = (JobPublic);

export type JobsReadJobData = {
    id: string;
};

export type JobsReadJobResponse = (JobPublic);

export type JobsUpdateJobData = {
    id: string;
    requestBody: JobUpdate;
};

export type JobsUpdateJobResponse = (JobPublic);

export type JobsDeleteJobData = {
    id: string;
};

export type JobsDeleteJobResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ScoreAnalyseScoreData = {
    requestBody: ScoreSchema;
};

export type ScoreAnalyseScoreResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type ScoreSaveScoreAnalysisData = {
    jobId: string;
    candidateFileName: string;
    scoreResult: {
        [key: string]: unknown;
    };
};

export type ScoreSaveScoreAnalysisResponse = (ScoreAnalysisPublic);

export type ScoreGetScoreAnalysisByJobData = {
    jobId: string;
};

export type ScoreGetScoreAnalysisByJobResponse = (Array<ScoreAnalysisPublic>);

export type ScoreGetScoreAnalysisByJobAndCandidateData = {
    jobId: string;
    candidateFileName: string;
};

export type ScoreGetScoreAnalysisByJobAndCandidateResponse = (ScoreAnalysisPublic);

export type ScoreAnalysisPublic = {
    id: string;
    job_id: string;
    candidate_file_name: string;
    score_result: string;
    created_at: string;
    updated_at: string;
};