"""add score analysis table

Revision ID: 108a92b85350
Revises: afe3bf5d379b
Create Date: 2025-06-24 10:54:03.573899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '108a92b85350'
down_revision = 'afe3bf5d379b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoreanalysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('score_result', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoreanalysis_candidate_file_name'), 'scoreanalysis', ['candidate_file_name'], unique=False)
    op.drop_column('job', 'score_analysis_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('score_analysis_result', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_scoreanalysis_candidate_file_name'), table_name='scoreanalysis')
    op.drop_table('scoreanalysis')
    # ### end Alembic commands ###
