"""add original_file_name to candidate analysis

Revision ID: ec4faf05951d
Revises: 61def211e877
Create Date: 2025-06-22 14:01:54.356010

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ec4faf05951d'
down_revision = '61def211e877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidateanalysis', sa.Column('original_file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_candidateanalysis_original_file_name'), 'candidateanalysis', ['original_file_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidateanalysis_original_file_name'), table_name='candidateanalysis')
    op.drop_column('candidateanalysis', 'original_file_name')
    # ### end Alembic commands ###
