/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutJobsImport } from './routes/_layout/jobs'
import { Route as LayoutJobScoringImport } from './routes/_layout/job-scoring'
import { Route as LayoutJobListImport } from './routes/_layout/job-list'
import { Route as LayoutJobEditingListImport } from './routes/_layout/job-editing-list'
import { Route as LayoutJobEditingImport } from './routes/_layout/job-editing'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJobsRoute = LayoutJobsImport.update({
  path: '/jobs',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJobScoringRoute = LayoutJobScoringImport.update({
  path: '/job-scoring',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJobListRoute = LayoutJobListImport.update({
  path: '/job-list',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJobEditingListRoute = LayoutJobEditingListImport.update({
  path: '/job-editing-list',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJobEditingRoute = LayoutJobEditingImport.update({
  path: '/job-editing',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/job-editing': {
      preLoaderRoute: typeof LayoutJobEditingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/job-editing-list': {
      preLoaderRoute: typeof LayoutJobEditingListImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/job-list': {
      preLoaderRoute: typeof LayoutJobListImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/job-scoring': {
      preLoaderRoute: typeof LayoutJobScoringImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/jobs': {
      preLoaderRoute: typeof LayoutJobsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutDashboardRoute,
    LayoutItemsRoute,
    LayoutJobEditingRoute,
    LayoutJobEditingListRoute,
    LayoutJobListRoute,
    LayoutJobScoringRoute,
    LayoutJobsRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
